# -*- coding: utf-8 -*-
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
"""
Generate Synthetic Sample Data for Lina's Analytics Module.

[WARNING] WARNING: ALL DATA GENERATED BY THIS SCRIPT IS SYNTHETIC DEMO DATA.
It is NOT real store data. It is generated to enable development,
testing, and model prototyping without real-world data.

The generated data simulates realistic daily crowd patterns:
- Low traffic early morning (08:00–10:00)
- Rising traffic mid-morning (10:00–12:00)
- Peak lunch period (12:00–14:00)
- Moderate afternoon traffic (14:00–17:00)
- Evening peak (17:00–19:00)
- Declining traffic (19:00–21:00)

Outputs (inside ai/lina/data/sample/):
    - people_tracks.json    -- tracking event list
    - queue_tracks.json     -- queue-specific events
    - historical_counts.csv -- aggregated historical data (30 days)
"""

import json
import math
import random
import csv
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Make src importable from scripts/
LINA_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(LINA_ROOT))

# ── Constants ────────────────────────────────────────────────────────────────
SYNTHETIC_LABEL = "SYNTHETIC DEMO DATA"
RANDOM_SEED = 42
random.seed(RANDOM_SEED)

STORE_WIDTH = 1000
STORE_HEIGHT = 800

ZONES = [
    {"id": "ZONE_A", "polygon": [[0, 0], [400, 0], [400, 300], [0, 300]]},
    {"id": "ZONE_B", "polygon": [[400, 0], [800, 0], [800, 300], [400, 300]]},
    {"id": "ZONE_C", "polygon": [[800, 0], [1000, 0], [1000, 300], [800, 300]]},
    {"id": "ZONE_D", "polygon": [[0, 300], [400, 300], [400, 600], [0, 600]]},
    {"id": "ZONE_E", "polygon": [[400, 300], [800, 300], [800, 600], [400, 600]]},
    {"id": "BILLING", "polygon": [[0, 600], [1000, 600], [1000, 800], [0, 800]]},
]

QUEUE_REGIONS = [
    {"id": "QUEUE_COUNTER_1", "polygon": [[0, 620], [200, 620], [200, 800], [0, 800]]},
    {"id": "QUEUE_COUNTER_2", "polygon": [[220, 620], [440, 620], [440, 800], [220, 800]]},
    {"id": "QUEUE_COUNTER_3", "polygon": [[460, 620], [680, 620], [680, 800], [460, 800]]},
]


# ── Crowd profile (hourly base people count) ─────────────────────────────────
HOURLY_PROFILE = {
    8:  12, 9:  20, 10: 35, 11: 50, 12: 75,
    13: 80, 14: 65, 15: 55, 16: 60, 17: 85,
    18: 90, 19: 70, 20: 45, 21: 20,
}


def get_crowd_count(hour: int, minute: int, day_of_week: int) -> int:
    """Return a realistic crowd count for a given time."""
    base = HOURLY_PROFILE.get(hour, 10)

    # Interpolate between hours
    next_hour_base = HOURLY_PROFILE.get((hour + 1) % 24, base)
    progress = minute / 60.0
    interpolated = base + (next_hour_base - base) * progress

    # Weekend boost
    if day_of_week >= 5:
        interpolated *= 1.25

    # Add realistic noise
    noise = random.gauss(0, max(interpolated * 0.08, 1))
    count = max(0, round(interpolated + noise))
    return count


def random_point_in_polygon(polygon: list) -> tuple[float, float]:
    """Generate a random point inside a polygon (bounding-box method)."""
    xs = [p[0] for p in polygon]
    ys = [p[1] for p in polygon]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    return (
        random.uniform(min_x + 5, max_x - 5),
        random.uniform(min_y + 5, max_y - 5),
    )


def generate_people_tracks(base_date: datetime, n_frames: int = 120) -> list[dict]:
    """
    Generate synthetic person tracking events.

    Args:
        base_date: Start datetime for the sequence.
        n_frames: Number of 30-second frames to generate.

    Returns:
        List of tracking event dicts.
    """
    events = []
    active_tracks: dict[int, dict] = {}  # track_id -> {zone, position}
    next_track_id = 1
    cameras = ["CAM01", "CAM02", "CAM03"]

    for frame_idx in range(n_frames):
        ts = base_date + timedelta(seconds=frame_idx * 30)
        hour, minute, dow = ts.hour, ts.minute, ts.weekday()
        target_count = get_crowd_count(hour, minute, dow)

        # Add new people if needed
        while len(active_tracks) < target_count:
            zone = random.choice(ZONES)
            cx, cy = random_point_in_polygon(zone["polygon"])
            active_tracks[next_track_id] = {"zone": zone["id"], "cx": cx, "cy": cy}
            next_track_id += 1

        # Remove some people naturally
        if len(active_tracks) > target_count:
            to_remove = random.sample(list(active_tracks.keys()),
                                       min(len(active_tracks) - target_count, 3))
            for tid in to_remove:
                del active_tracks[tid]

        # Small movement per frame
        for tid, state in active_tracks.items():
            state["cx"] = max(5, min(STORE_WIDTH - 5, state["cx"] + random.gauss(0, 8)))
            state["cy"] = max(5, min(STORE_HEIGHT - 5, state["cy"] + random.gauss(0, 8)))

        # Generate tracking event for each active track
        ts_str = ts.strftime("%Y-%m-%dT%H:%M:%S")
        for tid, state in active_tracks.items():
            cx, cy = state["cx"], state["cy"]
            w = random.uniform(30, 60)
            h = random.uniform(60, 120)
            event = {
                "timestamp": ts_str,
                "camera_id": random.choice(cameras),
                "track_id": tid,
                "class": "person",
                "confidence": round(random.uniform(0.75, 0.99), 2),
                "bbox": [
                    round(cx - w / 2, 1), round(cy - h / 2, 1),
                    round(cx + w / 2, 1), round(cy + h / 2, 1),
                ],
                "center": [round(cx, 1), round(cy, 1)],
                "_synthetic": SYNTHETIC_LABEL,
            }
            events.append(event)

    print(f"  Generated {len(events)} tracking events across {n_frames} frames")
    return events


def generate_queue_tracks(base_date: datetime, n_frames: int = 60) -> list[dict]:
    """Generate queue-specific synthetic tracking events."""
    events = []
    queue_tracks: dict[str, dict[int, dict]] = {q["id"]: {} for q in QUEUE_REGIONS}
    next_track_id = 5000

    for frame_idx in range(n_frames):
        ts = base_date + timedelta(seconds=frame_idx * 30)
        ts_str = ts.strftime("%Y-%m-%dT%H:%M:%S")

        for queue in QUEUE_REGIONS:
            queue_id = queue["id"]
            # Random queue length 0–8
            target_q_len = random.randint(0, 8)
            active = queue_tracks[queue_id]

            while len(active) < target_q_len:
                cx, cy = random_point_in_polygon(queue["polygon"])
                active[next_track_id] = {"cx": cx, "cy": cy}
                next_track_id += 1

            if len(active) > target_q_len and active:
                remove = list(active.keys())[:len(active) - target_q_len]
                for tid in remove:
                    del active[tid]

            for tid, state in active.items():
                state["cx"] += random.gauss(0, 3)
                state["cy"] += random.gauss(0, 3)
                cx, cy = state["cx"], state["cy"]
                events.append({
                    "timestamp": ts_str,
                    "camera_id": "CAM_BILLING",
                    "track_id": tid,
                    "class": "person",
                    "confidence": round(random.uniform(0.80, 0.99), 2),
                    "bbox": [round(cx - 20, 1), round(cy - 40, 1), round(cx + 20, 1), round(cy + 40, 1)],
                    "center": [round(cx, 1), round(cy, 1)],
                    "_synthetic": SYNTHETIC_LABEL,
                    "_queue_region": queue_id,
                })

    print(f"  Generated {len(events)} queue tracking events")
    return events


def generate_historical_counts(start_date: datetime, n_days: int = 30) -> list[dict]:
    """
    Generate 30 days of historical 5-minute aggregated crowd counts.

    Args:
        start_date: Start of the historical period.
        n_days: Number of days to generate.

    Returns:
        List of {timestamp, people_count, queue_length} dicts.
    """
    records = []
    current = start_date

    for day_idx in range(n_days):
        day = current + timedelta(days=day_idx)
        dow = day.weekday()

        for hour in range(8, 22):  # Store open 08:00 – 21:00
            for minute in range(0, 60, 5):
                ts = day.replace(hour=hour, minute=minute, second=0, microsecond=0)
                count = get_crowd_count(hour, minute, dow)
                queue_len = max(0, round(count * random.uniform(0.05, 0.15)))

                records.append({
                    "timestamp": ts.strftime("%Y-%m-%dT%H:%M:%S"),
                    "people_count": count,
                    "queue_length": queue_len,
                    "_synthetic": SYNTHETIC_LABEL,
                })

    print(f"  Generated {len(records)} historical records ({n_days} days)")
    return records


def save_json(data: list, filepath: Path) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"  Saved -> {filepath}")


def save_csv(data: list[dict], filepath: Path) -> None:
    if not data:
        return
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=data[0].keys())
        writer.writeheader()
        writer.writerows(data)
    print(f"  Saved -> {filepath}")


def main() -> None:
    print("=" * 60)
    print("LINA SAMPLE DATA GENERATOR")
    print("[WARNING] ALL DATA IS SYNTHETIC DEMO DATA")
    print("=" * 60)

    sample_dir = LINA_ROOT / "data" / "sample"
    sample_dir.mkdir(parents=True, exist_ok=True)

    base_date = datetime(2026, 9, 13, 9, 0, 0)
    historical_start = datetime(2026, 8, 14, 0, 0, 0)

    print("\n[1/3] Generating people tracking events...")
    tracks = generate_people_tracks(base_date, n_frames=120)
    save_json(tracks, sample_dir / "people_tracks.json")

    print("\n[2/3] Generating queue tracking events...")
    queue_tracks = generate_queue_tracks(base_date, n_frames=60)
    save_json(queue_tracks, sample_dir / "queue_tracks.json")

    print("\n[3/3] Generating 30-day historical crowd counts...")
    historical = generate_historical_counts(historical_start, n_days=30)
    save_csv(historical, sample_dir / "historical_counts.csv")

    print("\n[OK] Sample data generation complete!")
    print(f"   Output directory: {sample_dir}")
    print("\nNext steps:")
    print("  python scripts/train_prediction_model.py")
    print("  python scripts/run_demo.py")


if __name__ == "__main__":
    main()


